"""Initial Migration

Revision ID: 42688410048a
Revises: 14b03fa09cf5
Create Date: 2025-02-18 15:09:35.078589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42688410048a'
down_revision = '14b03fa09cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
